// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // static FirebaseOptions get currentPlatform {
  //   if (kIsWeb) {
  //     return web;
  //   }
  //   switch (defaultTargetPlatform) {
  //     case TargetPlatform.android:
  //       return android;
  //     case TargetPlatform.iOS:
  //       return ios;
  //     case TargetPlatform.macOS:
  //       return macos;
  //     case TargetPlatform.windows:
  //       return windows;
  //     case TargetPlatform.linux:
  //       throw UnsupportedError(
  //         'DefaultFirebaseOptions have not been configured for linux - '
  //         'you can reconfigure this by running the FlutterFire CLI again.',
  //       );
  //     default:
  //       throw UnsupportedError(
  //         'DefaultFirebaseOptions are not supported for this platform.',
  //       );
  //   }
  // }



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCoKINIuQaoa0n6rJK7NUkzU23x1UH5B2k",
    authDomain: "music-app-1ddca.firebaseapp.com",
    projectId: "music-app-1ddca",
    storageBucket: "music-app-1ddca.firebasestorage.app",
    messagingSenderId: "353479222961",
    appId: "1:353479222961:web:5b7041c21fa93667d52490",
  );

  
}
